### ISSUE TITLE
Docker on LibreELEC (Kodi)

### ISSUE THREAD

**Issue by xbmcnut** [aptalca/docker-ha-bridge#11]
Hi. Thanks for making this!

Trying to see if I can run ha-bridge in the background of a Kodi install on RPi2 with LibreELEC. Got the docker add-on installed and ran the following:

`docker run -d --name="Home-Automation-Bridge" --net="host" -e SERVERIP="192.168.137.8" -e SERVERPORT="80" -v /storage/downloads/habridge:/config:rw -e TZ="Pacific/Auckland" aptalca/home-automation-bridge`

It all seems to work as the container is created but when I run `docker ps -a` I get the following:
```
LibreELEC:~ # docker ps -a
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                     PORTS               NAMES
96cc921c5951        aptalca/home-automation-bridge   "/sbin/my_init"     9 seconds ago       Exited (1) 3 seconds ago                       Home-Automation-Bridge
```
How to I debug the exit issue?

**Comment by aptalca** [comment]
The container is for x86 and unfortunately won't work on rpi (arm). I may have created an arm version somewhere (unreleased, dev). I'll look into it.

**Comment by xbmcnut** [comment]
Thank you for your prompt reply and that is good to know! Save me burning the midnight hours trying to figure out why it won't work! If you have a dev version I could test on RPi2/3 that would be fantastic and I think a lot of people would be very keen on this. I have many friends that have an always on Pi with OpenELEC/LibreELEC that would benefit from having ha-bridge running on there as they start to explore the world of Google Home/Alexa integration.

**Comment by aptalca** [comment]
Alright, pushed an arm version to the repo. You can use the same parameters and the docker run command, just change the repo at the end to `aptalca/home-automation-bridge-arm`

And by the way, if you would like the container to auto-start on boot, you can add this to the run command: `--restart=always`

I tried installing it through portainer on LE and it was very straightforward. Let me know how it works

**Comment by xbmcnut** [comment]
That is awesome, thank you! Let me give that a try in the next 24hrs and I'll let you know.

**Comment by xbmcnut** [comment]
Success!!!! working with:
```
docker run -d --name="Home-Automation-Bridge" --restart=always --net="host" -e SER
VERIP="localhost" -e SERVERPORT="80" -v /storage/downloads/habridge:/config:rw -e TZ="Pacific/Au
ckland" aptalca/home-automation-bridge-arm
```
Thank you so much. Haven't actually tested ha-bridge yet as I have another instance on my network but web page is loading up and all looks good.

**Comment by xbmcnut** [comment]
In regards to updating (ha-bridge), can we just stop the image and restart it or the does the image have to be removed and re-downloaded?

**Comment by aptalca** [comment]
Glad to hear it works. Closing this issue.

A restart of the container should pull a new jar from bwssystems if there is an update. No need to recreate the container.

**Comment by rajsingh9471** [comment]
i have libreelec 8.2.5. when i m putting this code for ha bridge in putty, its showing docker not found, can anyone help me out
