### ISSUE TITLE
Synology Install fail

### ISSUE THREAD

**Issue by yaggayoyo** [aptalca/docker-ha-bridge#13]
I have installed this on my synology via Docker and following the instructions here: https://hub.docker.com/r/aptalca/home-automation-bridge/   but I cant seem to get the IP or page to login to portal. What am i doing wrong? The logs show no IP or Port despite my configure stating one.

**Comment by aptalca** [comment]
What settings did you use?

**Comment by yaggayoyo** [comment]
I used port 8810 in the command line to install app which is not used by synology. Within docker I see the app on the host network but I don't see port section filled out in app like command line defined.

**Comment by aptalca** [comment]
Please post the full docker run command you used.

**Comment by yaggayoyo** [comment]
sudo docker run -d --name="Home-Automation-Bridge" --net="host" -e SERVERIP="10.0.1.11” -e SERVERPORT="8810” -v /volume1/ha-bridge/:/config:rw -v /etc/localtime:/etc/localtime:ro aptalca/home-automation-bridge

**Comment by aptalca** [comment]
I'm assuming 10.0.1.11 is your synology IP. The container is using net=host so all ports are forwarded, it won't show port 8810 as forwarded. That parameter only tells the java app to serve the web gui on that port.

The run command looks good.

Can you post the output of `docker logs Home-Automation-Bridge`?

**Comment by yaggayoyo** [comment]
Yes, thats my synology IP.SO how do I access the web gui?

Logs below

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
stdout
18:27:42
*** Running /etc/my_init.d/firstrun.sh...
stdout
18:27:42
setting the correct local time
stdout
18:27:50
stdout
18:27:50
Current default time zone: 'Etc/UTC'
stdout
18:27:50
Local time is now:      Tue Mar 14 18:27:50 UTC 2017.
stdout
18:27:50
Universal Time is now:  Tue Mar 14 18:27:50 UTC 2017.
stdout
18:27:50
stdout
18:27:57
Latest version on bwssystems github repo is 4.2.1
stdout
18:27:57
Using existing version '4.2.1'
stdout
18:27:57
Setting correct permissions
stdout
18:27:57
Parameters used:
stdout
18:27:57
Server IP : 
stdout
18:27:57
Server Port : 
stdout
18:27:57
Starting Home Automation Bridge
stdout
18:28:02
2017-03-14 18:28:02,009 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.2.1) starting....
stdout
18:28:02
2017-03-14 18:28:02,216 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from system properties
stdout
18:28:02
Exception in thread &quot;main&quot; java.lang.NumberFormatException: For input string: &quot;&quot;
stdout
18:28:02
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
stdout
18:28:02
	at java.lang.Integer.parseInt(Integer.java:592)
stdout
18:28:02
	at java.lang.Integer.valueOf(Integer.java:766)
stdout
18:28:02
	at com.bwssystems.HABridge.BridgeSettingsDescriptor.setServerPort(BridgeSettingsDescriptor.java:76)
stdout
18:28:02
	at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:70)
stdout
18:28:02
	at com.bwssystems.HABridge.HABridge.main(HABridge.java:49)
stdout
18:28:02
*** Running /etc/rc.local...
stdout
18:28:02
*** Booting runit daemon...
stdout
18:28:02
*** Runit started as PID 43
stdout
18:28:04
Mar 14 18:28:03 DiskStation syslog-ng[50]: syslog-ng starting up; version='3.5.3'

**Comment by aptalca** [comment]
Your closing quotation mark looks different. Very subtle, but different. If it's a different character, docker may not be passing the parameter correctly.
Here's a copy paste from your post above: "10.0.1.11”
Here's how I type it: "10.0.1.11"
You can see the second quotation mark in yours is different, it's slanted.

**Comment by yaggayoyo** [comment]
Awesome catch. I fixed it and it now works. I can get to GUI. Now to figure out how to add devices. Specifically my AirFoil speakers. You wouldn't know how to do that would you?.

**Comment by aptalca** [comment]
Great!

You should be able to get help for that on the github page for the bridge. Link is in the readme of my repo.
