### ISSUE TITLE
ha-bridge-.jar

### ISSUE THREAD

**Issue by xbmcnut** [aptalca/docker-ha-bridge#14]
Re-downloaded version for arm on Pi on the same Pi I was using before for testing but now in a deployed environment with a new IP address (10.1.1.101). ha-bridge does not start now with the error log that it cannot find `ha-bridge-.jar` which of course, is not the name of the .jar file. Is there a typo in the latest code somewhere?

**Comment by aptalca** [comment]
If you didn't define the version parameter, it should just pull the latest, which is 4.5.0

I just did a fresh install and it pulled the latest for  me. 

Your issue may have been a connection issue to github. If the connection wasn't successful, it wouldn't figure out the latest version and maybe that's why it was blank in your case. Restarting it later should work.

**Comment by xbmcnut** [comment]
It managed to download the container ok so assuming GitHub connection good? It did not have a .jar file beyond 4.3.1 though. I renamed the 4.3.1.jar to ha-bridge-.jar and ha-bridge immediately started. Is that a ha-bridge issue or docker container issue?

**Comment by aptalca** [comment]
Docker images are downloaded from docker hub. Github connection is needed after the container starts and it looks for the latest release at this address: https://api.github.com/repos/bwssytems/ha-bridge/releases/latest and grabs the version number from there, appends it to the jar file name. In your case I'm assuming that the github connection failed and it was not able to retrieve the correct jar version.

Can you post a docker log?

**Comment by xbmcnut** [comment]
I'm back on site today so will grab some logs.

**Comment by moon86** [comment]
Hi, 

I'm having the same issue than @xbmcnut. I installed with the following command:
`docker run -d --name="habridge" --restart=always --net="host" -e SERVERIP="192.168
.1.253" -e SERVERPORT="80" -v /storage/downloads/habridge:/config:rw -v /etc/localtime:/etc/localti
me:ro aptalca/home-automation-bridge-arm`

Here are the logs:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> usermod: no changes
> -------------------------------------
>           _     _ _
>          | |___| (_) ___
>          | / __| | |/ _ \
>          | \__ \ | | (_) |
>          |_|___/ |_|\___/
>                |_|
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> Latest version on bwssystems github repo is
> Installing version
> Connecting to github.com (192.30.253.113:443)
> wget: server returned error: HTTP/1.1 404 Not Found
> Parameters used:
> Server IP : 192.168.1.253
> Server Port : 80
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar`

Also installed with the -e VERSION argument and it is still not working:
`docker run -d --name="habridge" --restart=always --net="host" -e SERVERIP="192.168
.1.253" -e SERVERPORT="80" -e VERSION="4.5.0" -v /storage/downloads/habridge:/config:rw -v /etc/loc
altime:/etc/localtime:ro aptalca/home-automation-bridge-arm`

I tried to rename the jarfile like @xbmcnut to /storage/downloads/habridge/ha-bridge-.jar
Still getting the issue:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> usermod: no changes
> -------------------------------------
>           _     _ _
>          | |___| (_) ___
>          | / __| | |/ _ \
>          | \__ \ | | (_) |
>          |_|___/ |_|\___/
>                |_|
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> Latest version on bwssystems github repo is
> Using existing version
> Parameters used:
> Server IP : 192.168.1.253
> Server Port : 80
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 2017-04-27 10:02:03,066 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:03,239 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:06,775 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:06,948 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:10,528 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:10,703 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:14,215 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:14,387 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:19,287 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:19,456 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:22,994 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:23,165 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:26,766 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:26,940 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:30,767 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:30,956 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:34,543 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:34,721 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:02:38,284 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0) starting....
> 2017-04-27 10:02:38,458 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:150)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> Error: An unexpected error occurred while trying to open file ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> Error: Unable to access jarfile ha-bridge-.jar
> 2017-04-27 10:03:02,173 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:02,342 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:05,994 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:06,163 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:09,812 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:09,980 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:13,575 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:13,748 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:17,293 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:17,462 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:21,082 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:21,251 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:24,825 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:24,995 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] syncing disks.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing...
> usermod: no changes
> -------------------------------------
>           _     _ _
>          | |___| (_) ___
>          | / __| | |/ _ \
>          | \__ \ | | (_) |
>          |_|___/ |_|\___/
>                |_|
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donations/
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    911
> User gid:    911
> -------------------------------------
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing...
> Latest version on bwssystems github repo is
> Using existing version
> Parameters used:
> Server IP : 192.168.1.253
> Server Port : 80
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 2017-04-27 10:03:34,667 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:34,838 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:38,476 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:38,645 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:42,196 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:42,369 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:46,021 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:46,192 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:49,714 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:49,882 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:53,465 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:53,635 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:03:57,202 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:03:57,371 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:04:00,950 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:04:01,119 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)
> 2017-04-27 10:04:04,735 [main] INFO  com.bwssystems.HABridge.HABridge - HA Bridge (v4.5.0rc1) starting....
> 2017-04-27 10:04:04,903 [main] INFO  com.bwssystems.HABridge.BridgeSettings - reading from config file: data/habridge.config
> Exception in thread "main" java.lang.NullPointerException
>         at com.bwssystems.HABridge.BridgeSettings.buildSettings(BridgeSettings.java:143)
>         at com.bwssystems.HABridge.HABridge.main(HABridge.java:51)

Any help would be welcome !
Thank you

**Comment by xbmcnut** [comment]
My apologies. I've been away and won't be back on-site for logs till Monday 1st May.

**Comment by aptalca** [comment]
@moon86 your container cannot connect to github therefore it cannot figure out the latest version or download it. You can manually download the latest version from bwssystems' website, drop it in the config folder and set the version tag to match the version. 

What platform are you running this on?

**Comment by moon86** [comment]
Hi aptalca, thank you for your feedback. I downloaded it manually and forced the version to 4.5.0.
First it diddn't work (logs said file ha-bridge-.jar was missing). So in the config folder I renamed ha-bridge-4.5.0.jar into ha-bridge-.jar and restarted the app, now it works.

**Comment by xbmcnut** [comment]
When I turned up on Monday, mine had fixed itself (after a reboot sometime in the last two weeks) and it was happily running 4.5.0.
