### ISSUE TITLE
habridge id different in openhab then specified in habridge

### ISSUE THREAD

**Issue by GravityRZ** [aptalca/docker-ha-bridge#22]
trying to add habridge to openhab.
i get a failed to create new user error
![image](https://user-images.githubusercontent.com/16853535/59563014-be7be300-9034-11e9-9630-6bf548a12bab.png)

the Hue hub id in openhab is way lower then current versions
it should be 00178820e229
i have put this number in the emulate hub filed but it does not seem to pass it along to openhab(or any other app)

is the error i get related to the lower hub version and where does this lower version come from?

**Comment by bwssytems** [comment]
@GravityRZ Please close this on this issue list as it is just for the docker implementation. The ha-bridge issues resides here: https://github.com/bwssytems/ha-bridge/issues

**Comment by GravityRZ** [comment]
ok clear
