### ISSUE TITLE
Can't get Alexa to find the bridge

### ISSUE THREAD

**Issue by markstubb** [aptalca/docker-ha-bridge#7]
The bridge is running inside a docker container on a MacOS Sierra box, v 1.12.1 of docker.  I forwarded in 8080/tcp as well as 1900 and 50000 UDP.  I see a lot of log activity but Alexa never discovers it.  Any one else doing the same thing?  Apparently due to the way docker works on MacOS, you can't use --net="host", and must manually forward the ports.  Is there another set of ports I need to forward?

**Comment by aptalca** [comment]
This container requires to be run in host mode. Not sure about potential osx and net host issues
